FROM php:7.1.4-fpm

RUN apt-get -qq update \
    && apt-get -qq install libxml2-dev libpq-dev \
    && docker-php-ext-install pdo xml pgsql

# 公開するポート番号
# http://docs.docker.jp/engine/reference/builder.html#env
EXPOSE 80
